// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "KonzeptGrün GalaBau",
    "city": "Limburgerhof",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "KonzeptGrün GalaBau",
  "heroSubline": "Garten- & Landschaftsbau in Limburgerhof & Umgebung",
  "services": [
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom Rohbaugarten zur fertigen Anlage: Planung, Erdarbeiten, Stützmauern, Rollrasen und Bepflanzung.",
      "intro": "Planung und Gestaltung machen wir selbst, nicht als Zukauf. Das ist auch der Teil, den Kunden am häufigsten nennen: Ihre Wünsche werden aufgenommen und um Vorschläge ergänzt, bevor der erste Bagger anrückt. Danach läuft der Garten in einem Zug, von den Erdarbeiten über Stützmauern, Stufen und Wege bis zu Rollrasen und Bepflanzung, damit am Ende keine Ansammlung von Einzelgewerken dasteht.",
      "bullets": [
        "Aufmaß vor Ort: Boden, Höhenunterschiede, Zufahrt und Bestand",
        "Gestaltungsvorschläge statt einer einzigen fertigen Idee",
        "Erdarbeiten, Stützmauern aus Winkelelementen, Stufen und Randeinfassungen",
        "Rollrasen, Beete und Bepflanzung als letzter Bauabschnitt",
        "Teich, Wasserlauf und Poolumfeld bauen wir im selben Projekt mit"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zugang, Boden und Höhen und klären, was baulich sinnvoll ist. Das Erstgespräch kostet nichts."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit einzelnen Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Höhenunterschieden, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten, Mauern und Terrasse meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        },
        {
          "q": "Bauen Sie auch Teich oder Pool mit ein?",
          "a": "Ja. Teiche, Wasserläufe und das Umfeld von Pools gehören zu unserem Leistungsbereich und werden am besten gleich mit dem Garten zusammen geplant, weil Erdarbeiten, Technik und Leitungen sonst zweimal anfallen."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Limburgerhof | KonzeptGrün GalaBau",
        "description": "Gartenneugestaltung für Limburgerhof und die Vorderpfalz: Planung, Erdarbeiten, Stützmauern, Rollrasen und Bepflanzung aus einer Hand."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Wege und Hofflächen in Naturstein oder Betonstein, mit tragfähigem Unterbau und geplanter Entwässerung.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, planen das Gefälle mit und klären die Entwässerung, bevor der erste Stein liegt. Naturstein verlegen wir genauso wie Betonstein: Der Aufbau darunter unterscheidet sich kaum, die Verlegung dafür deutlich.",
      "bullets": [
        "Einfahrt, Zufahrt, Wege, Hof und Terrassenflächen",
        "Natursteinpflaster und Betonstein, auch im Anschluss an Bestandsflächen",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Entwässerung, Rinnen und Versickerung mitgeplant",
        "Randeinfassungen und Rasenkanten sauber eingebunden"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder eine Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Limburgerhof | KonzeptGrün GalaBau",
        "description": "Pflasterarbeiten für Einfahrt, Wege und Hofflächen in Limburgerhof und Umgebung: Naturstein und Betonstein, tragfähiger Unterbau, geplante Entwässerung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus großformatigen Platten, Naturstein oder Holz, inklusive Unterbau und Randabschluss.",
      "intro": "Die Terrasse ist der Teil des Gartens, der täglich benutzt wird. Ob sie nach fünf Jahren noch eben liegt, entscheiden Unterbau und Gefälle, nicht das Muster im Prospekt. Großformatige Platten bauen wir besonders häufig, weil sie wenig Fuge und damit wenig Pflege bedeuten, dafür aber einen sehr genauen Unterbau verlangen.",
      "bullets": [
        "Großformatplatten, Keramik, Naturstein, Betonplatten und Holz",
        "Unterbau: Splittbett, Stelzlager oder Punktfundamente",
        "Anschlusshöhen an Tür und Schwelle vorab geprüft",
        "Randabschluss und Übergang zu Rasen oder Beet mitgeplant",
        "Leerrohre für Licht und Strom liegen vor dem Belag"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Holz oder Platte?",
          "a": "Holz ist warm und lebendig, braucht aber jährliche Pflege. Keramik, Naturstein und Betonplatten sind pflegeleicht und farbstabil. Wir zeigen beides an realen Flächen, bevor Sie sich festlegen."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Limburgerhof | KonzeptGrün GalaBau",
        "description": "Terrassenbau in Limburgerhof und der Vorderpfalz: Großformatplatten, Naturstein oder Holz, mit geplantem Unterbau, Gefälle und Randabschluss."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmalige Pflege oder feste Termine über die Saison: Rasen, Hecken, Beete und Saisonarbeiten.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn ein Garten aus dem Ruder gelaufen ist, und die laufende Pflege über die Saison. Gärten, die wir selbst gebaut haben, übernehmen wir auf Wunsch direkt nach der Übergabe, dann kennt die Anlage niemand besser.",
      "bullets": [
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Heckenschnitt, Formschnitt und Rückschnitt von Sträuchern",
        "Laubräumung und Frühjahrsputz auf Wunsch"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder über die Saison, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen, wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Limburgerhof | KonzeptGrün GalaBau",
        "description": "Gartenpflege in Limburgerhof und Umgebung: Einmalpflege oder feste Termine über die Saison, Rasen, Heckenschnitt, Beete und Laubräumung."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Zäune, Sichtschutzwände, Geländer und Gabionen, kalkuliert nach laufenden Metern.",
      "intro": "Zaun und Sichtschutz rechnen sich nach laufenden Metern. Entscheidend sind Höhe, Fundament und Grenzverlauf. Geländer an Mauern, Stufen und Terrassenkanten bauen wir mit, weil sie ohnehin zum selben Höhenversprung gehören. Wo eine Genehmigung oder eine Absprache mit dem Nachbarn nötig ist, sagen wir das vorher und nicht erst beim Setzen der Pfosten.",
      "bullets": [
        "Doppelstabmatten, Holz, WPC, Aluminium und Gabionen",
        "Geländer an Stützmauern, Stufen und Terrassenkanten",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Hinweise zu Grenzverlauf, Höhe und örtlicher Satzung",
        "Tore und Türen mit passender Beschlagtechnik"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, in Rheinland-Pfalz sind an der Grenze häufig rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Sichtschutzwänden, Geländern und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun, Sichtschutz & Geländer in Limburgerhof | KonzeptGrün GalaBau",
        "description": "Zaun, Sichtschutz und Geländer nach laufenden Metern: Doppelstabmatten, Holz, Gabionen, mit Fundament und Hinweisen zur Genehmigung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Limburgerhof",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Limburgerhof, von Mannheim und Ludwigshafen über Speyer und Schifferstadt bis Neustadt und Germersheim. Weiter entfernte Projekte prüfen wir einzeln und sagen lieber sofort ab, als Sie drei Wochen warten zu lassen.",
    "plzPrefixes": [
      "67",
      "68",
      "69"
    ],
    "borderPlzPrefixes": [
      "64",
      "74",
      "76"
    ],
    "places": [
      "Limburgerhof",
      "Schifferstadt",
      "Ludwigshafen am Rhein",
      "Mannheim",
      "Speyer",
      "Frankenthal",
      "Neustadt an der Weinstraße",
      "Bad Dürkheim",
      "Schwetzingen",
      "Hockenheim",
      "Heidelberg",
      "Germersheim"
    ],
    "center": {
      "lat": 49.4200917,
      "lng": 8.3855955
    }
  },
  "contact": {
    "phone": "01517 2585137",
    "phoneLink": "tel:+4915172585137",
    "whatsapp": "01517 2585137",
    "whatsappLink": "https://wa.me/4915172585137",
    "whatsappPrefill": "Hallo KonzeptGrün GalaBau, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Helfer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Unsere Baustellen liegen rund um Limburgerhof, meist im Umkreis von 40 km. Gebaut wird der ganze Garten, nicht ein einzelner Handgriff: Erdarbeiten, Mauern, Pflaster, Terrasse, Rasen und Pflege wechseln sich ab. Erzählen Sie uns kurz, was Sie können, den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in",
      "Auszubildende/r"
    ],
    "benefits": [
      "Baustellen in der Region, Feierabend zu Hause statt Montage",
      "Abwechslung statt Kolonne: Pflaster, Neuanlage, Mauern und Pflege im Wechsel",
      "Kurze Wege, Entscheidungen fallen auf der Baustelle",
      "Pünktliche Lohnzahlung und geregelte Arbeitszeiten",
      "Maschinenscheine und Weiterbildung sind möglich"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Planung im Haus",
        "text": "Gestaltung und Planung machen wir selbst. Genau das nennen Kunden in den Bewertungen am häufigsten: Wünsche aufgenommen, um eigene Ideen ergänzt."
      },
      {
        "label": "Über zehn Jahre im Beruf",
        "text": "Gelernter Landschaftsgärtner, groß geworden im Handwerk des Vaters, der fast 30 Jahre im Garten- und Landschaftsbau gearbeitet hat."
      },
      {
        "label": "Termine, die halten",
        "text": "Erstberatung kostenlos, Aufmaß vor dem Preis, feste Bauzeit vor dem ersten Spatenstich."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
