// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.5,
  "totalRatings": 6,
  "reviews": [
    {
      "author": "Fritz Germeier",
      "rating": 5,
      "text": "Wir sind absolut zufrieden mit der Arbeit von KonzeptGrün GalaBau! Die Planung war professionell, die Umsetzung sauber und zuverlässig. Unsere Wünsche wurden perfekt umgesetzt und mit tollen Ideen ergänzt. Das Ergebnis ist ein wunderschöner Garten, den wir jeden Tag genießen. Klare Empfehlung – vielen Dank an das ganze Team!",
      "time": "vor einem Jahr"
    },
    {
      "author": "Besnik Beljuli",
      "rating": 5,
      "text": "Ich bin äußerst zufrieden mit der Arbeit von konzeptgrün GaLaBau. Das Team überzeugt durch professionelle Planung, kreative Gestaltung und zuverlässige Umsetzung – alles mit Blick auf Nachhaltigkeit und höchste Qualität. Unser Garten ist jetzt ein echtes Highlight geworden  vielen Dank!",
      "time": "vor einem Jahr"
    },
    {
      "author": "Mandy Muriqi",
      "rating": 5,
      "text": "Sehr gute Arbeit. Man kann nichts negatives über die Firma sagen. Sehr gute Qualität.  Preis Leistungsverhältnis ist auch top. Wir sind sehr sehr zufrieden .",
      "time": "vor einem Jahr"
    },
    {
      "author": "Fatlind Zeqiraj",
      "rating": 5,
      "text": "Terminabwicklung und Umsetzung reibungslos. Sehr begeistert mit der Arbeit, und nur zu empfehlen! Danke noch einmal!",
      "time": "vor einem Jahr"
    }
  ]
};
